# Generated by Django 5.1 on 2024-08-28 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nie', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('tiempo_marchena', models.IntegerField()),
                ('tiempo_espana', models.IntegerField()),
                ('nivel_espanol', models.CharField(max_length=50)),
                ('nivel_estudios', models.CharField(max_length=100)),
                ('situacion_laboral', models.CharField(max_length=100)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('familiares', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_vivienda', models.CharField(max_length=100)),
                ('comparte_vivienda', models.CharField(max_length=100)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('derivacion', models.TextField(blank=True, null=True)),
                ('asistencias', models.JSONField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.BinaryField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
    ]
