# Generated by Django 5.1 on 2024-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='asistencias',
            field=models.TextField(),
        ),
    ]
