# Generated by Django 5.1 on 2024-09-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_persona_asistencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='comparte_vivienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_vivienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
